### ISSUE TITLE
When installing Yii2 queue

### ISSUE THREAD

**Issue by pptyasar** [isaacs/abbrev-js#19]
[RuntimeException]                                                                                                                                                     
  Failed to execute git clone --mirror 'git+ssh://git@github.com/isaacs/abbrev-js.git' '/home/developer/.composer/cache/vcs/git-ssh---git-github.com-isaacs-abbrev-js.g  
  it/'                      

                                                                                                                                                                         
  Cloning into bare repository '/home/developer/.composer/cache/vcs/git-ssh---git-github.com-isaacs-abbrev-js.git'...                                                    
  Permission denied (publickey).                                                                                                                                         
  fatal: Could not read from remote repository.

**Comment by isaacs** [comment]
I don't understand this issue or how it's related to this module.  It seems like a composer thing?
